<?php
/**
 * WPML Integration - creates and links translated posts.
 *
 * API surface
 * -----------
 * WPML documents its hooks (`apply_filters`/`do_action`) as the only public,
 * stability-guaranteed surface. The global `$sitepress` object and the
 * `icl_*` functions still work in 4.9 but are undocumented or deprecated, so
 * they are used only as fallbacks here.
 *
 * Why post writes go through wp_insert_post()/wp_update_post()
 * -----------------------------------------------------------
 * A previous version wrote `post_content` with `$wpdb->update()` on the posts
 * table to dodge `content_save_pre` filters. That had two serious consequences:
 *
 *  1. `save_post` never fired, so WPML's own `WPML_TM_Post_Actions` never
 *     recorded translation status. Translations kept showing as missing or
 *     "needs update" in the WPML dashboard even though they existed.
 *     Elementor, SEO plugins and caches were equally left stale.
 *
 *  2. It bypassed `wp_filter_post_kses`, storing unfiltered markup for users
 *     without the `unfiltered_html` capability — a stored-XSS vector, since
 *     the content is generated by an external AI service.
 *
 * Block markup survives `wp_update_post()` perfectly well: that is how the
 * block editor itself saves. The only filter that genuinely corrupts block
 * markup is `balanceTags`, which is disabled here for the duration of the
 * write and restored immediately afterwards.
 */

if (!defined('ABSPATH')) {
    exit;
}

class WIT_WPML_Integration {

    private static $instance = null;

    public static function instance() {
        if (is_null(self::$instance)) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    private function __construct() {}

    // -----------------------------------------------------------------------
    // Language helpers
    // -----------------------------------------------------------------------

    /**
     * WPML's normalised element type for a post type ("post_page", "post_product").
     *
     * @param string $post_type
     * @return string
     */
    private function element_type($post_type) {
        return apply_filters('wpml_element_type', $post_type);
    }

    /**
     * All active WPML languages.
     *
     * @return array[] List of {code, name, english_name, default}
     */
    public function get_active_languages() {
        $languages = apply_filters('wpml_active_languages', null, array('skip_missing' => 0));

        if (!is_array($languages)) {
            return array();
        }

        $default = $this->get_default_language();
        $engine  = new WIT_Translator_Engine();
        $out     = array();

        foreach ($languages as $code => $language) {
            $code = isset($language['code']) ? $language['code'] : $code;

            // wpml_active_languages has no English name — only native_name and
            // translated_name, the latter in the admin's display language
            // ("Inglés" for a Spanish admin). The engine's table gives the
            // English one that instructions to a model need.
            $english = $engine->get_language_name($code);

            $out[] = array(
                'code'         => $code,
                'name'         => isset($language['native_name']) ? $language['native_name'] : $code,
                'english_name' => ($english !== '' && $english !== $code)
                    ? $english
                    : (isset($language['translated_name']) ? $language['translated_name'] : $code),
                'default'      => ($code === $default),
            );
        }

        return $out;
    }

    /**
     * Whether a language code is an active WPML language.
     *
     * Guards against writing arbitrary codes into WPML's tables.
     *
     * @param string $code
     * @return bool
     */
    public function is_active_language($code) {
        foreach ($this->get_active_languages() as $language) {
            if ($language['code'] === $code) {
                return true;
            }
        }
        return false;
    }

    /**
     * The site's default language code.
     *
     * @return string
     */
    public function get_default_language() {
        $code = apply_filters('wpml_default_language', null);

        return $code ? $code : 'en';
    }

    /**
     * The language of a post.
     *
     * @param int $post_id
     * @return string Empty string when unknown.
     */
    public function get_post_language($post_id) {
        $code = apply_filters('wpml_element_language_code', null, array(
            'element_id'   => $post_id,
            'element_type' => $this->element_type(get_post_type($post_id)),
        ));

        return $code ? $code : '';
    }

    /**
     * The translation group id (trid) of a post.
     *
     * @param int $post_id
     * @return int|null
     */
    private function get_trid($post_id) {
        $trid = apply_filters(
            'wpml_element_trid',
            null,
            $post_id,
            $this->element_type(get_post_type($post_id))
        );

        return $trid ? (int) $trid : null;
    }

    /**
     * The id of an existing translation, if any.
     *
     * @param int    $post_id
     * @param string $target_language
     * @return int|false
     */
    public function get_translation_id($post_id, $target_language) {
        $post_type = get_post_type($post_id);

        if (!$post_type) {
            return false;
        }

        $translated_id = apply_filters('wpml_object_id', $post_id, $post_type, false, $target_language);

        // A post is not a translation of itself.
        if (!$translated_id || (int) $translated_id === (int) $post_id) {
            return false;
        }

        return get_post_status($translated_id) ? (int) $translated_id : false;
    }

    // -----------------------------------------------------------------------
    // Listing posts
    // -----------------------------------------------------------------------

    /**
     * List source-language posts that the current user may translate.
     *
     * @param string   $target_language
     * @param string[] $post_types
     * @param bool     $only_pending Exclude posts that already have a translation.
     * @param int      $limit
     * @param string   $search       Optional text to search for.
     * @return array[]
     */
    public function get_pending_translations($target_language, $post_types = array('post', 'page'), $only_pending = false, $limit = 100, $search = '') {
        if (empty($target_language) || !$this->is_active_language($target_language)) {
            return array();
        }

        // Only allow post types that actually exist and are registered.
        $post_types = array_values(array_filter(
            array_map('sanitize_key', (array) $post_types),
            'post_type_exists'
        ));

        if (empty($post_types)) {
            return array();
        }

        $default_language = $this->get_default_language();

        // Query in the source language. suppress_filters is left on so WPML's
        // own query filtering applies.
        $query = new WP_Query(array(
            'post_type'              => $post_types,
            'post_status'            => array('publish', 'draft', 'pending', 'private', 'future'),
            'posts_per_page'         => (int) $limit,
            'orderby'                => 'modified',
            'order'                  => 'DESC',
            'ignore_sticky_posts'    => true,
            'no_found_rows'          => true,
            'update_post_term_cache' => false,
            'suppress_filters'       => false,
            'lang'                   => $default_language,
            's'                      => (string) $search,
        ));

        $posts = array();

        foreach ($query->posts as $post) {
            // Never expose a post the current user cannot edit.
            if (!current_user_can('edit_post', $post->ID)) {
                continue;
            }

            // Skip posts that are themselves translations.
            if ($this->get_post_language($post->ID) !== $default_language) {
                continue;
            }

            $translation_id = $this->get_translation_id($post->ID, $target_language);

            if ($only_pending && $translation_id) {
                continue;
            }

            $posts[] = array(
                'id'                   => $post->ID,
                'title'                => $post->post_title !== '' ? $post->post_title : __('(sin título)', 'wpml-imagina-translate'),
                'type'                 => $post->post_type,
                'status'               => $post->post_status,
                'edit_url'             => get_edit_post_link($post->ID, 'raw'),
                'translation_exists'   => (bool) $translation_id,
                'translation_id'       => $translation_id ? $translation_id : 0,
                'translation_edit_url' => $translation_id ? get_edit_post_link($translation_id, 'raw') : '',
            );
        }

        return $posts;
    }

    // -----------------------------------------------------------------------
    // Creating and updating translations
    // -----------------------------------------------------------------------

    /**
     * Create a translated post and link it to the source in WPML.
     *
     * @param int    $source_post_id
     * @param string $target_language
     * @param array  $data {title, content, excerpt}
     * @return int|WP_Error
     */
    public function create_translated_post($source_post_id, $target_language, $data) {
        $source = get_post($source_post_id);

        if (!$source) {
            return new WP_Error('invalid_post', __('Post original no encontrado', 'wpml-imagina-translate'));
        }

        if (!$this->is_active_language($target_language)) {
            return new WP_Error('invalid_language', __('El idioma destino no está activo en WPML', 'wpml-imagina-translate'));
        }

        /**
         * Filter the post status given to newly created translations.
         *
         * @param string  $status
         * @param WP_Post $source
         * @param string  $target_language
         */
        $status = apply_filters('wit_new_translation_status', 'draft', $source, $target_language);

        $postarr = array(
            'post_title'     => $data['title'],
            'post_content'   => $data['content'],
            'post_excerpt'   => isset($data['excerpt']) ? $data['excerpt'] : '',
            'post_status'    => $status,
            'post_type'      => $source->post_type,
            'post_author'    => $source->post_author,
            'post_parent'    => $this->translated_parent($source, $target_language),
            'menu_order'     => $source->menu_order,
            'comment_status' => $source->comment_status,
            'ping_status'    => $source->ping_status,
        );

        $new_post_id = $this->insert_post($postarr, false);

        if (is_wp_error($new_post_id)) {
            return $new_post_id;
        }

        $source_language = $this->get_post_language($source_post_id);

        $this->link_translation($source_post_id, $new_post_id, $target_language);
        $this->copy_taxonomies($source_post_id, $new_post_id, $target_language, $source_language);
        $this->copy_meta($source_post_id, $new_post_id);
        $this->copy_featured_image($source_post_id, $new_post_id, $target_language);

        return $new_post_id;
    }

    /**
     * Update an existing translation with freshly translated content.
     *
     * @param int   $post_id        The translation.
     * @param array $data           {title, content, excerpt}
     * @param int   $source_post_id When given, taxonomies and the featured
     *                              image are re-synced from it too: the source
     *                              is the source of truth, and the content is
     *                              being regenerated from it anyway.
     * @return true|WP_Error
     */
    public function update_translated_post($post_id, $data, $source_post_id = 0) {
        $postarr = array(
            'ID'           => $post_id,
            'post_title'   => $data['title'],
            'post_content' => $data['content'],
        );

        if (!empty($data['excerpt'])) {
            $postarr['post_excerpt'] = $data['excerpt'];
        }

        $result = $this->insert_post($postarr, true);

        if (is_wp_error($result)) {
            return $result;
        }

        if ($source_post_id) {
            $target_language = $this->get_post_language($post_id);
            $source_language = $this->get_post_language($source_post_id);

            if ($target_language) {
                $this->copy_taxonomies($source_post_id, $post_id, $target_language, $source_language);
                $this->copy_featured_image($source_post_id, $post_id, $target_language);
            }
        }

        return true;
    }

    /**
     * Copy the custom fields a translation would otherwise lose.
     *
     * Page template, ACF fields, Elementor page settings, layout flags: a
     * translation created without them renders differently from its source,
     * or not at all. Fields configured for translation are overwritten by the
     * translation step afterwards; fields handled elsewhere and WordPress/WPML
     * housekeeping keys are left out.
     *
     * Creation only. A re-translation regenerates the content, but whatever
     * the reviewer changed in other fields of the translation stays theirs.
     *
     * @param int $source_post_id
     * @param int $target_post_id
     * @return int Keys copied.
     */
    private function copy_meta($source_post_id, $target_post_id) {
        $all = get_post_meta($source_post_id);

        if (!is_array($all) || empty($all)) {
            return 0;
        }

        $skip_exact = array(
            '_edit_lock', '_edit_last', '_wp_old_slug', '_wp_old_date',
            '_wp_desired_post_slug', '_pingme', '_encloseme',
            '_thumbnail_id',                    // copy_featured_image() resolves the translated media
            '_last_translation_edit_mode',
        );
        // _elementor_* is WIT_Elementor_Handler's: it translates the data,
        // copies the settings keys and clears the render caches itself.
        // _wit_ is this plugin's bookkeeping about a translation (the source
        // fingerprint used to detect outdated translations); copying it from
        // the source would make a fresh translation look like a stale one.
        $skip_prefix = array('_elementor_', '_icl_', '_wpml_', '_wit_', '_wp_trash_meta_', '_oembed_');

        $copied = 0;

        foreach ($all as $key => $values) {
            if (in_array($key, $skip_exact, true)) {
                continue;
            }
            foreach ($skip_prefix as $prefix) {
                if (strpos($key, $prefix) === 0) {
                    continue 2;
                }
            }

            /**
             * Filter whether a custom field is copied to a new translation.
             *
             * @param bool   $copy
             * @param string $key
             * @param int    $source_post_id
             * @param int    $target_post_id
             */
            if (!apply_filters('wit_copy_meta_key', true, $key, $source_post_id, $target_post_id)) {
                continue;
            }

            delete_post_meta($target_post_id, $key);

            foreach ((array) $values as $value) {
                // get_post_meta() hands back serialized strings, and
                // add_post_meta() expects slashed, unserialized input.
                add_post_meta($target_post_id, $key, wp_slash(maybe_unserialize($value)));
            }

            $copied++;
        }

        return $copied;
    }

    /**
     * Insert or update a post without letting content filters rewrite the markup.
     *
     * Two filters are suspended for the duration of the write and restored
     * immediately afterwards, even if the write throws.
     *
     * balanceTags() re-nests HTML and reliably corrupts block markup. It is off
     * by default but plenty of sites enable it.
     *
     * wp_filter_post_kses() runs whenever the acting user lacks `unfiltered_html`
     * — which is every Author and Contributor, every non-super-admin on
     * multisite, and every cron or WP-CLI run, since those have no current user
     * at all. It deletes iframe, svg, script, style and form elements from the
     * stored HTML and entity-encodes `&`, `<` and `>` inside block attribute
     * values. Leaving it enabled would silently degrade the translation
     * relative to the source post, and would do so differently depending on who
     * happened to click the button.
     *
     * Suspending it is safe here specifically because this plugin never
     * introduces new markup:
     *
     *   - The document is rebuilt with core's own serialize_blocks(), whose
     *     serialize_block_attributes() applies the same escaping that the XSS
     *     fix in WP 5.3.1 introduced.
     *   - Translated text is written into text nodes by WIT_HTML_Translator,
     *     which HTML-escapes `&`, `<` and `>` first. A provider that returned
     *     "<script>alert(1)</script>" stores it as visible, inert text.
     *   - Everything else is the source post's own content, which was already
     *     filtered when that post was saved.
     *
     * @param array $postarr Unslashed post data.
     * @param bool  $update  True to update an existing post.
     * @return int|WP_Error
     */
    private function insert_post(array $postarr, $update) {
        $suspended = array();

        foreach (array('content_save_pre', 'content_filtered_save_pre', 'excerpt_save_pre') as $hook) {
            foreach (array('wp_filter_post_kses', 'balanceTags') as $callback) {
                $priority = has_filter($hook, $callback);
                if ($priority !== false) {
                    remove_filter($hook, $callback, $priority);
                    $suspended[] = array($hook, $callback, $priority);
                }
            }
        }

        try {
            // wp_insert_post() expects slashed data and runs wp_unslash() on it
            // before writing. Without wp_slash() every backslash in the block
            // attribute JSON is eaten: "<" becomes "u003c", the JSON stops
            // decoding, and the block loses all of its attributes silently.
            return $update
                ? wp_update_post(wp_slash($postarr), true)
                : wp_insert_post(wp_slash($postarr), true);
        } finally {
            // Restoring in `finally` matters: leaking a suspended kses filter
            // into the rest of the request would disable HTML filtering
            // site-wide for that request.
            foreach ($suspended as $entry) {
                add_filter($entry[0], $entry[1], $entry[2]);
            }
        }
    }

    /**
     * Resolve the translated parent of a hierarchical post.
     *
     * Without this, translations of child pages are all created at the root and
     * the target language loses the page hierarchy and its permalinks.
     *
     * @param WP_Post $source
     * @param string  $target_language
     * @return int
     */
    private function translated_parent(WP_Post $source, $target_language) {
        if (!$source->post_parent) {
            return 0;
        }

        $translated_parent = $this->get_translation_id($source->post_parent, $target_language);

        return $translated_parent ? $translated_parent : 0;
    }

    /**
     * Link a translation to its source in WPML's translation group.
     *
     * @param int    $source_post_id
     * @param int    $translated_post_id
     * @param string $target_language
     */
    private function link_translation($source_post_id, $translated_post_id, $target_language) {
        $element_type    = $this->element_type(get_post_type($source_post_id));
        $source_language = $this->get_post_language($source_post_id);

        if (!$source_language) {
            $source_language = $this->get_default_language();
        }

        $trid = $this->get_trid($source_post_id);

        if (!$trid) {
            // The source post is not registered with WPML yet; registering it
            // without a trid creates a new translation group.
            do_action('wpml_set_element_language_details', array(
                'element_id'    => $source_post_id,
                'element_type'  => $element_type,
                'trid'          => false,
                'language_code' => $source_language,
            ));

            $trid = $this->get_trid($source_post_id);
        }

        if (!$trid) {
            return;
        }

        do_action('wpml_set_element_language_details', array(
            'element_id'           => $translated_post_id,
            'element_type'         => $element_type,
            'trid'                 => $trid,
            'language_code'        => $target_language,
            'source_language_code' => $source_language,
        ));
    }

    /**
     * Assign the translated equivalents of the source post's terms.
     *
     * @param int    $source_post_id
     * @param int    $translated_post_id
     * @param string $target_language
     */
    /**
     * Names and descriptions of the terms a translation would have to create.
     *
     * Walks exactly what copy_taxonomies() and create_translated_term() walk —
     * every term of every taxonomy on the post that has no translation yet,
     * plus any untranslated ancestors, since a child is created under its
     * translated parent — so an MCP plan asks for every string the term step
     * will look up. Anything missed here would reach the external map as a
     * gap, and the term would keep its source-language name.
     *
     * @param int    $source_post_id
     * @param string $target_language
     * @return string[]
     */
    public function collect_missing_term_strings($source_post_id, $target_language) {
        $strings = array();
        $seen    = array();

        foreach (get_object_taxonomies(get_post_type($source_post_id)) as $taxonomy) {
            $terms = wp_get_object_terms($source_post_id, $taxonomy, array('fields' => 'ids'));

            if (is_wp_error($terms) || empty($terms)) {
                continue;
            }

            foreach ($terms as $term_id) {
                // Climb to the root, stopping at the first ancestor that is
                // already translated — create_translated_term() does the same.
                $current = (int) $term_id;

                while ($current && !isset($seen[$taxonomy . ':' . $current])) {
                    $seen[$taxonomy . ':' . $current] = true;

                    if (apply_filters('wpml_object_id', $current, $taxonomy, false, $target_language)) {
                        break;
                    }

                    $term = get_term($current, $taxonomy);

                    if (!$term || is_wp_error($term)) {
                        break;
                    }

                    if (!apply_filters('wit_create_missing_terms', true, $term, $target_language)) {
                        break;
                    }

                    $strings[] = $term->name;
                    if ($term->description !== '') {
                        $strings[] = $term->description;
                    }

                    $current = (int) $term->parent;
                }
            }
        }

        return array_values(array_unique($strings));
    }

    private function copy_taxonomies($source_post_id, $translated_post_id, $target_language, $source_language = '') {
        $taxonomies = get_object_taxonomies(get_post_type($source_post_id));

        foreach ($taxonomies as $taxonomy) {
            $terms = wp_get_object_terms($source_post_id, $taxonomy, array('fields' => 'ids'));

            if (is_wp_error($terms) || empty($terms)) {
                continue;
            }

            $assign = array();

            foreach ($terms as $term_id) {
                $translated_term_id = apply_filters('wpml_object_id', $term_id, $taxonomy, false, $target_language);

                if ($translated_term_id) {
                    $assign[] = (int) $translated_term_id;
                    continue;
                }

                // No translation yet. Create one so the translated post keeps
                // its taxonomy: the previous behaviour skipped the term
                // entirely, which left translations with no categories at all
                // and broke archives, menus and SEO silently.
                $created = $this->create_translated_term($term_id, $taxonomy, $target_language, $source_language);

                // Falling back to the source term is still better than leaving
                // the post uncategorised.
                $assign[] = $created ? $created : (int) $term_id;
            }

            $assign = array_values(array_unique(array_filter($assign)));

            if (!empty($assign)) {
                wp_set_object_terms($translated_post_id, $assign, $taxonomy);
            }
        }
    }

    /**
     * Create the translation of a term and link it to the original in WPML.
     *
     * @param int    $term_id
     * @param string $taxonomy
     * @param string $target_language
     * @param string $source_language
     * @return int|false New term id, or false when it could not be created.
     */
    private function create_translated_term($term_id, $taxonomy, $target_language, $source_language) {
        $term = get_term($term_id, $taxonomy);

        if (!$term || is_wp_error($term)) {
            return false;
        }

        /**
         * Filter whether missing terms may be created during translation.
         *
         * @param bool     $create
         * @param WP_Term  $term
         * @param string   $target_language
         */
        if (!apply_filters('wit_create_missing_terms', true, $term, $target_language)) {
            return false;
        }

        // Name and description in one request rather than one each.
        $sources = array($term->name);
        if ($term->description !== '') {
            $sources[] = $term->description;
        }

        $engine  = new WIT_Translator_Engine();
        $results = $engine->translate_batch($sources, $target_language, $source_language);

        $name = (empty($results[0]['error']) && $results[0]['translation'] !== '')
            ? $results[0]['translation']
            : $term->name;

        $description = '';
        if ($term->description !== '') {
            $description = (empty($results[1]['error']) && $results[1]['translation'] !== '')
                ? $results[1]['translation']
                : $term->description;
        }

        // Translate the parent first so hierarchy survives.
        $parent = 0;
        if ($term->parent) {
            $translated_parent = apply_filters('wpml_object_id', $term->parent, $taxonomy, false, $target_language);
            $parent = $translated_parent
                ? (int) $translated_parent
                : (int) $this->create_translated_term($term->parent, $taxonomy, $target_language, $source_language);
        }

        // The clean slug when it is free. WPML itself only appends the language
        // code on a collision; doing it unconditionally put "-en" into every
        // translated archive URL.
        $slug = sanitize_title($name);
        if ($slug === '' || term_exists($slug, $taxonomy)) {
            $slug = sanitize_title($name . '-' . $target_language);
        }

        $created = wp_insert_term($name, $taxonomy, array(
            'description' => $description,
            'parent'      => $parent,
            'slug'        => $slug,
        ));

        if (is_wp_error($created)) {
            // A term with this name may already exist unlinked; adopt it.
            $existing = $created->get_error_data('term_exists');
            if (!$existing) {
                return false;
            }
            $existing_term = get_term((int) $existing, $taxonomy);
            if (!$existing_term || is_wp_error($existing_term)) {
                return false;
            }
            $created = array(
                'term_id'          => (int) $existing_term->term_id,
                'term_taxonomy_id' => (int) $existing_term->term_taxonomy_id,
            );
        }

        $new_term_id = (int) $created['term_id'];

        // Link the new term into the original's translation group.
        //
        // WPML keys taxonomy rows on term_taxonomy_id; only wpml_object_id
        // takes a term_id. Passing term_id here worked by coincidence while the
        // two counters happened to match, and on any site that had ever
        // deleted a term it linked translations to unrelated terms — in
        // testing, "Servicios" resolved to the English "Marketing".
        $element_type = apply_filters('wpml_element_type', $taxonomy);
        $source_tt_id = (int) $term->term_taxonomy_id;
        $trid         = apply_filters('wpml_element_trid', null, $source_tt_id, $element_type);

        if (!$trid) {
            // The source term has no language yet (it predates WPML, or was
            // created by code that bypassed it). Without a group to join, every
            // run would create one more duplicate translation. Register it.
            do_action('wpml_set_element_language_details', array(
                'element_id'           => $source_tt_id,
                'element_type'         => $element_type,
                'trid'                 => null,
                'language_code'        => $source_language ?: $this->get_default_language(),
                'source_language_code' => null,
            ));
            $trid = apply_filters('wpml_element_trid', null, $source_tt_id, $element_type);
        }

        if ($trid) {
            do_action('wpml_set_element_language_details', array(
                'element_id'           => (int) $created['term_taxonomy_id'],
                'element_type'         => $element_type,
                'trid'                 => $trid,
                'language_code'        => $target_language,
                'source_language_code' => $source_language ?: $this->get_default_language(),
            ));
        }

        return $new_term_id;
    }

    /**
     * @param int    $source_post_id
     * @param int    $translated_post_id
     * @param string $target_language
     */
    private function copy_featured_image($source_post_id, $translated_post_id, $target_language) {
        $thumbnail_id = get_post_thumbnail_id($source_post_id);

        if (!$thumbnail_id) {
            return;
        }

        // Prefer the translated attachment when WPML has one, so the alt text
        // and caption are in the right language. The `true` argument makes WPML
        // fall back to the original attachment when no translation exists.
        $translated_thumbnail = apply_filters('wpml_object_id', $thumbnail_id, 'attachment', true, $target_language);

        set_post_thumbnail($translated_post_id, $translated_thumbnail ? (int) $translated_thumbnail : $thumbnail_id);
    }
}
